USE sprint1;

CREATE TABLE usuario (
idUser INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
senha VARCHAR(100) NOT NULL,
idade INT NOT NULL,
cargo VARCHAR(50)
);

CREATE TABLE sensor (
idSensor INT PRIMARY KEY AUTO_INCREMENT,
modelo CHAR(4) DEFAULT 'MQ-2',
dtInstalacao DATE NOT NULL,
statuss VARCHAR(20) DEFAULT 'ATIVO',
CONSTRAINT chkStatus CHECK(statuss IN ('ATIVO','MANUTENÇÃO','INATIVO'))
);

CREATE TABLE leitura_sensor (
idLeitura INT PRIMARY KEY AUTO_INCREMENT,
idSensor INT NOT NULL,
valorBruto INT NOT NULL,
vazamento BOOLEAN,
dtHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);